export const VIDEOS = [
  {
    id: 1,
    title: "Comment l'IA va changer notre façon de coder",
    channel: "TechMada",
    avatar: "TM",
    avatarBg: "#185FA5",
    avatarColor: "#E6F1FB",
    views: "1,2M",
    time: "il y a 3 jours",
    duration: "18:42",
    cat: "Tech",
    color1: "#0F6E56",
    color2: "#1D9E75",
    description: "Dans cette vidéo, on explore comment l'intelligence artificielle transforme le monde du développement logiciel. Des outils comme GitHub Copilot et Claude changent radicalement la façon dont les développeurs travaillent.",
  },
  {
    id: 2,
    title: "J'ai joué 100 heures sur ce jeu — voici mon avis complet",
    channel: "GamingMG",
    avatar: "GM",
    avatarBg: "#533AB7",
    avatarColor: "#EEEDFE",
    views: "890K",
    time: "il y a 1 semaine",
    duration: "24:17",
    cat: "Gaming",
    color1: "#3C3489",
    color2: "#7F77DD",
    description: "Après 100 heures de jeu intensif, voici mon avis honnête et complet. Points forts, points faibles, est-ce que ça vaut vraiment le prix ? Je réponds à toutes vos questions.",
  },
  {
    id: 3,
    title: "Les meilleurs spots cachés de Madagascar 🌿",
    channel: "VoyageAfrique",
    avatar: "VA",
    avatarBg: "#D85A30",
    avatarColor: "#FAECE7",
    views: "2,4M",
    time: "il y a 5 jours",
    duration: "12:08",
    cat: "Voyage",
    color1: "#993C1D",
    color2: "#D85A30",
    description: "Madagascar regorge de merveilles cachées que peu de touristes connaissent. Dans cette vidéo, je vous emmène découvrir des lieux extraordinaires loin des sentiers battus.",
  },
  {
    id: 4,
    title: "Recette authentique du romazava — cuisine malgache",
    channel: "CuisineMada",
    avatar: "CM",
    avatarBg: "#BA7517",
    avatarColor: "#FAEEDA",
    views: "340K",
    time: "il y a 2 semaines",
    duration: "9:55",
    cat: "Cuisine",
    color1: "#854F0B",
    color2: "#EF9F27",
    description: "Le romazava est le plat national malgache par excellence. Aujourd'hui je vous partage la recette de ma grand-mère, authentique et savoureuse. Ingrédients simples, résultat exceptionnel.",
  },
  {
    id: 5,
    title: "Physique quantique expliquée simplement en 15 minutes",
    channel: "ScienceTV",
    avatar: "ST",
    avatarBg: "#3B6D11",
    avatarColor: "#EAF3DE",
    views: "5,1M",
    time: "il y a 1 mois",
    duration: "15:33",
    cat: "Science",
    color1: "#27500A",
    color2: "#639922",
    description: "La physique quantique n'est pas aussi compliquée qu'on le croit. En 15 minutes, je vous explique les concepts fondamentaux : superposition, intrication, et principe d'incertitude.",
  },
  {
    id: 6,
    title: "Lo-fi beats pour travailler & se concentrer · 2h de mix",
    channel: "LoFiStudio",
    avatar: "LS",
    avatarBg: "#993556",
    avatarColor: "#FBEAF0",
    views: "12M",
    time: "il y a 3 mois",
    duration: "2:04:00",
    cat: "Musique",
    color1: "#72243E",
    color2: "#D4537E",
    description: "2 heures de musique lo-fi parfaite pour étudier, travailler ou simplement se détendre. Pas de publicité, pas d'interruption. Juste de la bonne musique.",
  },
  {
    id: 7,
    title: "Créer une app React en 1 heure — tutoriel complet 2026",
    channel: "CodeAfrique",
    avatar: "CA",
    avatarBg: "#185FA5",
    avatarColor: "#E6F1FB",
    views: "567K",
    time: "il y a 4 jours",
    duration: "1:02:15",
    cat: "Tech",
    color1: "#0C447C",
    color2: "#378ADD",
    description: "Apprenez à créer votre première application React from scratch en moins d'une heure. Idéal pour les débutants. On couvre les hooks, le state, les composants et le déploiement.",
  },
  {
    id: 8,
    title: "Ranked jusqu'au diamant — live stream highlights",
    channel: "GamingMG",
    avatar: "GM",
    avatarBg: "#533AB7",
    avatarColor: "#EEEDFE",
    views: "203K",
    time: "il y a 2 jours",
    duration: "35:50",
    cat: "Gaming",
    color1: "#26215C",
    color2: "#534AB7",
    description: "Les meilleurs moments de mon live stream où j'ai réussi à atteindre le rang Diamant. Clutches impossibles, plays incroyables et quelques fails hilarants.",
  },
];

export const CATEGORIES = ["Tout", "Tech", "Gaming", "Musique", "Voyage", "Science", "Cuisine"];
